name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y rsync ssh

    - name: Deploy to DigitalOcean Droplet
      env:
        DIGITALOCEAN_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ root@${{ env.DIGITALOCEAN_HOST }}:/home/

    - name: Restart service on DigitalOcean Droplet
      env:
        DIGITALOCEAN_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ env.DIGITALOCEAN_HOST }} 'systemctl restart nginx'
