// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/product/product.proto (package product, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateProductRequest, CreateProductResponse, DeleteProductRequest, DeleteProductResponse, GetProductRequest, GetProductResponse, UpdateProductRequest, UpdateProductResponse } from "./product_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The Product service definition.
 *
 * @generated from service product.ProductService
 */
export const ProductService = {
  typeName: "product.ProductService",
  methods: {
    /**
     * @generated from rpc product.ProductService.CreateProduct
     */
    createProduct: {
      name: "CreateProduct",
      I: CreateProductRequest,
      O: CreateProductResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.ProductService.GetProduct
     */
    getProduct: {
      name: "GetProduct",
      I: GetProductRequest,
      O: GetProductResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.ProductService.UpdateProduct
     */
    updateProduct: {
      name: "UpdateProduct",
      I: UpdateProductRequest,
      O: UpdateProductResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.ProductService.DeleteProduct
     */
    deleteProduct: {
      name: "DeleteProduct",
      I: DeleteProductRequest,
      O: DeleteProductResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

