// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/sensor/sensor.proto (package sensor, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateSensorRequest, CreateSensorResponse, DeleteSensorRequest, DeleteSensorResponse, GetSensorRequest, GetSensorResponse, UpdateSensorRequest, UpdateSensorResponse } from "./sensor_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The Sensor service definition.
 *
 * @generated from service sensor.SensorService
 */
export const SensorService = {
  typeName: "sensor.SensorService",
  methods: {
    /**
     * @generated from rpc sensor.SensorService.CreateSensor
     */
    createSensor: {
      name: "CreateSensor",
      I: CreateSensorRequest,
      O: CreateSensorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sensor.SensorService.GetSensor
     */
    getSensor: {
      name: "GetSensor",
      I: GetSensorRequest,
      O: GetSensorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sensor.SensorService.UpdateSensor
     */
    updateSensor: {
      name: "UpdateSensor",
      I: UpdateSensorRequest,
      O: UpdateSensorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sensor.SensorService.DeleteSensor
     */
    deleteSensor: {
      name: "DeleteSensor",
      I: DeleteSensorRequest,
      O: DeleteSensorResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

