// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/schema/schema.proto (package schema, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateSchemaRequest, CreateSchemaResponse, DeleteSchemaRequest, DeleteSchemaResponse, GetSchemaRequest, GetSchemaResponse, UpdateSchemaRequest, UpdateSchemaResponse } from "./schema_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The Schema service definition.
 *
 * @generated from service schema.SchemaService
 */
export const SchemaService = {
  typeName: "schema.SchemaService",
  methods: {
    /**
     * @generated from rpc schema.SchemaService.CreateSchema
     */
    createSchema: {
      name: "CreateSchema",
      I: CreateSchemaRequest,
      O: CreateSchemaResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc schema.SchemaService.GetSchema
     */
    getSchema: {
      name: "GetSchema",
      I: GetSchemaRequest,
      O: GetSchemaResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc schema.SchemaService.UpdateSchema
     */
    updateSchema: {
      name: "UpdateSchema",
      I: UpdateSchemaRequest,
      O: UpdateSchemaResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc schema.SchemaService.DeleteSchema
     */
    deleteSchema: {
      name: "DeleteSchema",
      I: DeleteSchemaRequest,
      O: DeleteSchemaResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

