models:
  - name: Schema
    fields:
      - name: id
        type: int32
        primary_key: true
        auto_increment: true
      - name: name
        type: string
      - name: content
        type: string
